# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyiTunes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTunes

  # Api
  pod 'Alamofire'
  pod 'ObjectMapper'
  
  #UI
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher'
  pod 'TagListView'
  pod 'SVProgressHUD'
  
end
